{% set name = "trustllm" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/trustllm-{{ version }}.tar.gz
  sha256: 818d003c408b8b7b4e0a191c91f1b8c7d44192610d4b023696afe5a94bcb5ace

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - transformers
    - numpy >=1.18.1
    - scipy
    - pandas >=1.0.3
    - scikit-learn
    - openai
    - tqdm
    - tenacity

test:
  imports:
    - trustllm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/HowieHwong/TrustLLM
  summary: "TrustLLM: A Benchmark of Trustworthiness in Large Language Models"
  license: MIT
  license_file: LICENSE
  description: |

    PyPI: [https://pypi.org/project/{{ name | lower }}/](https://pypi.org/project/{{ name | lower }}/)

  doc_url: https://HowieHwong.github.io/TrustLLM
  dev_url: https://github.com/HowieHwong/TrustLLM

extra:
  recipe-maintainers:
    - sugatoray
